### ISSUE TITLE
Too many checks per minute

### ISSUE THREAD

**Issue by awesomemoder316** [jake-walker/instagram-discord-bridge#12]
I have an issue where the program will check too many times a minute, giving an ugly error. Is there a way to prevent this error, rather than just catching it? 

```
(node:57585) UnhandledPromiseRejectionWarning: IgResponseError: GET /api/v1/direct_v2/inbox/?visual_message_return_type=unseen&thread_message_limit=10&persistentBadging=true&limit=20 - 429 Too Many Requests; Please wait a few minutes before you try again.
at Request.handleResponseError (/home/ubuntu/instagram-discord-bridge/node_modules/instagram-private-api/dist/core/request.js:125:16)
at Request.send (/home/ubuntu/instagram-discord-bridge/node_modules/instagram-private-api/dist/core/request.js:53:28)
(node:57585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: "x")
```
where "x" is initially 1, which increases by one every time error is thrown.

**Comment by awesomemoder316** [comment]
Messages seem to not link as a result of the this (rate limiting??)

**Comment by jake-walker** [comment]
Yes, this problem is because of rate limiting. Ideally this would be fixed by checking for rate limiting and increasing the interval between checks, although I'm not really supporting this project anymore.

As a quick fix, you could edit the 1 second interval between message checks to something longer in `instagram.js`:

https://github.com/jake-walker/instagram-discord-bridge/blob/11a30cb8acde00520b695f19d9ac9f2f9782bd8d/instagram.js#L65
